spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSLDialect
    hibernate:
      ddl-auto:
        update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: /%MP6qD|}jTt9FIN(H~9j=jiciS*v&dY,VY8B9+*E4UaW-uHr^+_hU^Ed'@NV+"
      expiration: 8640000 #1day
  mailing:
    frontend:
      activateAccountUrl: http://localhost:4200/activate-account